name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: server
        use-pylint: no
        use-pycodestyle: no
        use-flake8: no
        use-black: yes
        use-mypy: yes
        use-isort: yes
